import { useState, type FormEvent } from 'react';
import { ArrowLeft, ArrowRight, LockKeyhole, Mail, ShieldCheck } from 'lucide-react';

export default function ForgotPassword({ lang, onBack }: { lang: 'en' | 'th'; onBack: () => void }) {
 const th = lang === 'th';
 const [email, setEmail] = useState('');
 const [touched, setTouched] = useState(false);
 const [submitted, setSubmitted] = useState(false);
 const error = !email.trim() ? (th ? 'กรุณากรอกอีเมล' : 'Email address is required.') : !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim()) ? (th ? 'กรุณากรอกอีเมลให้ถูกต้อง' : 'Please enter a valid email address.') : '';
 function submit(event: FormEvent) { event.preventDefault(); setTouched(true); if (error) { document.getElementById('reset-email')?.focus(); return; } setSubmitted(true); }
 return <div className="form-content forgot-content"><div className="form-symbol"><LockKeyhole size={24}/></div><h2>{th ? 'รีเซ็ตรหัสผ่านของคุณ' : 'Reset your password'}</h2><>{submitted ? <div className="reset-sent"><p className="form-subtitle">{th ? 'ตรวจสอบอีเมลของคุณ' : 'Check your email'}</p><div className="reset-success" role="status"><Mail size={18} aria-hidden="true"/><span>{th ? 'ส่งลิงก์รีเซ็ตรหัสผ่านแล้ว (จำลอง) หากอีเมลนี้มีบัญชี ลิงก์จะใช้ได้ครั้งเดียวและมีอายุจำกัด' : 'Reset link sent (demo). If that address has an account, a reset link is on its way. It works once and expires shortly after it is sent.'}</span></div><p className="reset-help">{th ? 'ยังไม่ได้รับอีเมล? ตรวจสอบโฟลเดอร์สแปมก่อน แล้วลองอีกครั้ง' : 'Nothing arrived? Check your spam folder first, then try again.'}</p><button className="primary-button" onClick={()=>{setSubmitted(false);setEmail('');setTouched(false);requestAnimationFrame(()=>document.getElementById('reset-email')?.focus());}}>{th ? 'ใช้อีเมลอื่น' : 'Use a different address'}</button></div> : <><p className="form-subtitle">{th ? 'กรอกอีเมลที่ใช้สมัครบัญชี เพื่อขอลิงก์สำหรับตั้งรหัสผ่านใหม่' : 'Enter the email address on your account to request a link to choose a new password.'}</p><form noValidate onSubmit={submit}><div className="field"><label htmlFor="reset-email">{th ? 'อีเมล' : 'Email address'}</label><div className={`input-wrap ${touched && error ? 'invalid' : ''}`}><Mail size={18} aria-hidden="true"/><input id="reset-email" type="email" autoComplete="email" required placeholder="name@company.com" value={email} onChange={event => {setEmail(event.target.value);setSubmitted(false);}} onBlur={()=>setTouched(true)} aria-invalid={Boolean(touched && error)} aria-describedby={touched && error ? 'reset-email-error' : undefined}/></div>{touched && error && <p id="reset-email-error" className="field-error">{error}</p>}</div><button className="primary-button" type="submit">{th ? 'ส่งลิงก์รีเซ็ตรหัสผ่าน' : 'Send reset link'}<ArrowRight size={17}/></button>{submitted && <p className="reset-feedback" role="status">{th ? 'อีเมลผ่านการตรวจสอบแล้ว โหมดตัวอย่างนี้ยังไม่ได้เชื่อมต่อบริการส่งอีเมล จึงยังไม่มีการส่งลิงก์รีเซ็ตรหัสผ่าน' : 'Email validated. This preview is not connected to an email service, so no reset link has been sent.'}</p>}</form></>}</><div className="divider"><span/></div><button className="text-button back-button" onClick={onBack}><ArrowLeft size={14}/>{th ? 'กลับไปเข้าสู่ระบบ' : 'Back to sign in'}</button><p className="preview-note"><ShieldCheck size={14}/>{th ? 'โหมดตัวอย่าง · ไม่มีการส่งหรือบันทึกข้อมูล' : 'Preview mode · No data is sent or saved.'}</p></div>;
}
